export const GET_ALL_DATA = 'GET_ALL_DATA';
export const GET_ONE_DATA = 'GET_ONE_DATA';
export const CREATE_DATA = 'CREATE_DATA';
export const EDIT_DATA = 'EDIT_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';

export const UPDATE_DATA_FAILED = 'UPDATE_DATA_FAILED';
export const CREATE_DATA_FAILED = 'CREATE_DATA_FAILED';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';

export const UPDATE_STATUS_FAILED = 'UPDATE_STATUS_FAILED';
export const CREATE_STATUS_FAILED = 'CREATE_STATUS_FAILED';
export const GET_STATUS_FAILED = 'GET_STATUS_FAILED';
